### ISSUE TITLE
Falta archivo

### ISSUE THREAD

**Issue by dfbarrero** [TecnologiaVideojuegos/proyectovideojuego-equipo-h#1]
Falta archivo './resources/sprites/player/Akimbo.png', por favor añadirlo al repositorio con urgencia o consideraré que el juego no es funcional.

**Comment by ersabajanes** [comment]
Buenas tardes David,

Ya he subido el archivo Akimbo.png al repositorio y cerrado el issue que
habías puesto. Creo que el problema ha sido que Windows (el sistema
operativo que tenemos casi todos los integrantes del grupo) no distingue
entre mayúsculas y minúsculas por lo que es posible que se nos escapase
alguna y no nos diésemos cuenta.

Disculpe las molestias.

Eduardo Ruiz del equipo H.
